import os
from traceback import print_tb
import eauth
import platform
from datetime import datetime
now = datetime.now()
my_system = platform.uname()
print("[+] initializing api")
eauth.time.sleep(0.5)
print("[+] attached to server")
eauth.time.sleep(1)
os.system('cls')
os.system("PAUSE")
def main_f():
    os.system('cls')
    print("▒█▀▀▀ ░█▀▀█ ▒█░▒█ ▀▀█▀▀ ▒█░▒█ ")
    print("▒█▀▀▀ ▒█▄▄█ ▒█░▒█ ░▒█░░ ▒█▀▀█ ")
    print("▒█▄▄▄ ▒█░▒█ ░▀▄▄▀ ░▒█░░ ▒█░▒█")
    print(" ")
    print(" ")
    print("[ 1 ] Login     [ 2 ] Register")
    print(" ")
    current_time = now.strftime("%X")
    print("[",current_time,"]",end=" ")
    value = input("user@eauth:~$ ")
    if value == "1":
        os.system('cls')
        username = input("Username: ")
        password = input("Password: ")
        eauth.signin(username,password)
        os.system('cls')
        print(eauth.Loggedmessage)
        print(" ")
        print("Username: " + eauth.ins.Username)
        print("Rank: " + eauth.ins.Rank)
        print("Create Date: " + eauth.ins.CreateDate)
        print("Expire Date: " + eauth.ins.ExpireDate)
        print("Hardware ID: " + eauth.ins.HardwareID)
        # print("Variable: " + eauth.grabvariable("your variable id here"))
        eauth.time.sleep(3)
        main_f()
    elif value == "2":
        os.system('cls')
        username = input("Username: ")
        password = input("Password: ")
        invite = input("License Key: ")
        eauth.signup(username,password,invite)
        eauth.time.sleep(1.5)
        main_f()
    else:
        os.system('cls')
        print("Invalid input!")
        eauth.time.sleep(1)
        main_f()
main_f()
os.system("PAUSE")
